---
- hosts: all
  tasks:
    - name: Reboot all machines
      become: yes
      reboot:
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 30
        test_command: uptime