- name: Install Python {{ python_version }} & pip
  apt:
    name:
      - python{{ python_version }}
      - python3-pip
    state: present

- name: Set default Python version to {{ python_version }}
  alternatives:
    name: python
    path: /usr/bin/python{{ python_version }}
    link: /usr/bin/python

- name: Install pip packages
  pip:
    name: "{{ item }}"
  loop: "{{ extra_pip_packages }}"