- name: Generate & Fetch master public key
  when: inventory_hostname in groups['master']
  block:
    - name: Generate public key
      become: yes
      user:
        name: ubuntu
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
      register: user_output

    - name: Fetch public key
      become: yes
      fetch:
        src: "{{ user_output.ssh_key_file }}.pub"
        dest: /tmp/id_dgl_master.pub
        flat: yes

- name: Add master public key to all nodes
  become: yes
  authorized_key:
    user: {{ ansible_user }}
    key: "{{ lookup('file', '/tmp/id_dgl_master.pub') }}"

- name: Restart SSH service
  systemd:
    name: ssh
    state: restarted
  become: yes